//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntecedenteDental
    {
        public int nAntecedenteDentalID { get; set; }
        public int nExpedienteID { get; set; }
        public Nullable<System.DateTime> dFechaUltimaVisitaDentista { get; set; }
        public string sMotivoVisita { get; set; }
        public string sExperienciaAsistencial { get; set; }
        public byte nTratamientoQuirurgico { get; set; }
        public byte nTratamientoRestauracion { get; set; }
        public byte nTratamientoPeridoncia { get; set; }
        public byte nTratamientoEndodoncia { get; set; }
        public byte nTratamientoOrtodoncia { get; set; }
        public byte nTratamientoProtesis { get; set; }
        public byte nColocadoAnestesia { get; set; }
        public byte nReaccionAlergicaAnestesia { get; set; }
        public string sReaccionAlergicaAnestesia { get; set; }
        public string sDescripcionTejidosBlandos { get; set; }
        public string sHistoriaEnfermedadActual { get; set; }
        public int nEstadoID { get; set; }
        public System.DateTime dFechaCreacion { get; set; }
        public string sUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> dFechaModificacion { get; set; }
        public string sUsuarioModificacion { get; set; }
    
        public virtual Expediente Expediente { get; set; }
    }
}
