//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamenComplementario
    {
        public int nExamenComplementarioID { get; set; }
        public int nExpedienteID { get; set; }
        public byte nEstudiosRadiologicos { get; set; }
        public string sDescripcionER { get; set; }
        public byte nEstudiosLaboratorio { get; set; }
        public string sDescripcionEL { get; set; }
        public int nEstadoID { get; set; }
        public System.DateTime dFechaCreacion { get; set; }
        public string sUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> dFechaModificacion { get; set; }
        public string sUsuarioModificacion { get; set; }
    
        public virtual Expediente Expediente { get; set; }
    }
}
