//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int nMenuItemID { get; set; }
        public Nullable<int> nMenuItemPadreID { get; set; }
        public int nNivel { get; set; }
        public string sIconClass { get; set; }
        public string sDescripcion { get; set; }
        public string sAction { get; set; }
        public string sController { get; set; }
        public string sLink { get; set; }
    }
}
