//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Expediente = new HashSet<Expediente>();
        }
    
        public int nPacienteID { get; set; }
        public int nCodigo { get; set; }
        public string sNombre { get; set; }
        public string sApellido1 { get; set; }
        public string sApellido2 { get; set; }
        public int nGeneroID { get; set; }
        public string sLugarNacimiento { get; set; }
        public System.DateTime dFechaNacimiento { get; set; }
        public string sDireccion { get; set; }
        public string sCedula { get; set; }
        public string sTelefono { get; set; }
        public string sEmergenciaNombre { get; set; }
        public string sEmergenciaParentesco { get; set; }
        public string sEmergenciaTelefono { get; set; }
        public int nEstadoID { get; set; }
        public System.DateTime dFechaCreacion { get; set; }
        public string sUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> dFechaModificacion { get; set; }
        public string sUsuarioModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expediente> Expediente { get; set; }
    }
}
