//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodontograma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Periodontograma()
        {
            this.PeriodontogramaDetalle = new HashSet<PeriodontogramaDetalle>();
        }
    
        public int nPeriodontogramaID { get; set; }
        public int nExpedienteID { get; set; }
        public System.DateTime dFechaPeriodontograma { get; set; }
        public int nEstadoID { get; set; }
        public System.DateTime dFechaCreacion { get; set; }
        public string sUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> dFechaModificacion { get; set; }
        public string sUsuarioModificacion { get; set; }
    
        public virtual Expediente Expediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriodontogramaDetalle> PeriodontogramaDetalle { get; set; }
    }
}
