//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacagramaDetalle
    {
        public int nPlacagramaDetalleID { get; set; }
        public int nPlacagramaID { get; set; }
        public int nDienteID { get; set; }
        public int nSimboloID { get; set; }
        public int nEstadoID { get; set; }
        public System.DateTime dFechaCreacion { get; set; }
        public string sUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> dFechaModificacion { get; set; }
        public string sUsuarioModificacion { get; set; }
    
        public virtual Diente Diente { get; set; }
        public virtual Placagrama Placagrama { get; set; }
        public virtual Simbolo Simbolo { get; set; }
    }
}
