//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIGECO_Entities : DbContext
    {
        public SIGECO_Entities()
            : base("name=SIGECO_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AntecedenteDental> AntecedenteDental { get; set; }
        public virtual DbSet<AntecedenteFamiliar> AntecedenteFamiliar { get; set; }
        public virtual DbSet<Catalogo> Catalogo { get; set; }
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Diente> Diente { get; set; }
        public virtual DbSet<ExamenComplementario> ExamenComplementario { get; set; }
        public virtual DbSet<Expediente> Expediente { get; set; }
        public virtual DbSet<Odontograma> Odontograma { get; set; }
        public virtual DbSet<OdontogramaDetalle> OdontogramaDetalle { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Periodontograma> Periodontograma { get; set; }
        public virtual DbSet<PeriodontogramaDetalle> PeriodontogramaDetalle { get; set; }
        public virtual DbSet<Placagrama> Placagrama { get; set; }
        public virtual DbSet<PlacagramaDetalle> PlacagramaDetalle { get; set; }
        public virtual DbSet<Simbolo> Simbolo { get; set; }
        public virtual DbSet<Tratamiento> Tratamiento { get; set; }
        public virtual DbSet<TratamientoRealizado> TratamientoRealizado { get; set; }
        public virtual DbSet<ValorCatalogo> ValorCatalogo { get; set; }
        public virtual DbSet<vwOdontogramaDetalle> vwOdontogramaDetalle { get; set; }
    }
}
