//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIGECO_Entities : DbContext
    {
        public SIGECO_Entities()
            : base("name=SIGECO_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catalogo> Catalogo { get; set; }
        public virtual DbSet<Diente> Diente { get; set; }
        public virtual DbSet<Simbolo> Simbolo { get; set; }
        public virtual DbSet<ValorCatalogo> ValorCatalogo { get; set; }
        public virtual DbSet<SimboloDiente> SimboloDiente { get; set; }
        public virtual DbSet<vwSimboloDiente> vwSimboloDiente { get; set; }
    }
}
