//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableColumns
    {
        public int Id { get; set; }
        public string TABLE_SCHEMA { get; set; }
        public string TABLE_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public string CAPTION { get; set; }
        public Nullable<int> ORDINAL_POSITION { get; set; }
        public string COLUMN_DEFAULT { get; set; }
        public string HTML_TYPE { get; set; }
        public string HTML_PATTERN { get; set; }
        public string DATA_TYPE { get; set; }
        public Nullable<int> MAX_LENGTH { get; set; }
        public Nullable<bool> NULLABLE { get; set; }
        public Nullable<int> NUMERIC_PRECISION { get; set; }
        public Nullable<int> NUMERIC_SCALE { get; set; }
        public Nullable<bool> IS_FK { get; set; }
        public string TABLE_FK { get; set; }
        public string COLUMN_FK { get; set; }
        public Nullable<bool> HTML_ADD_SHOW { get; set; }
        public Nullable<bool> HTML_EDIT_SHOW { get; set; }
        public Nullable<bool> HTML_LIST_SHOW { get; set; }
        public Nullable<bool> HTML_ADD_LOCK { get; set; }
        public Nullable<bool> HTML_EDIT_LOCK { get; set; }
    }
}
