//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TratamientoRealizado
    {
        public int nTratamientoRealizadoID { get; set; }
        public int nExpedienteID { get; set; }
        public int nTratamientoID { get; set; }
        public System.DateTime dFechaTratamiento { get; set; }
        public decimal nAbono { get; set; }
        public int nMonedaAbonoID { get; set; }
        public int nEstadoID { get; set; }
        public System.DateTime dFechaCreacion { get; set; }
        public string sUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> dFechaModificacion { get; set; }
        public string sUsuarioModificacion { get; set; }
    
        public virtual Expediente Expediente { get; set; }
        public virtual Tratamiento Tratamiento { get; set; }
        public virtual ValorCatalogo ValorCatalogo { get; set; }
    }
}
