//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGECO
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSimboloDiente
    {
        public int nExpedienteID { get; set; }
        public int nDienteID { get; set; }
        public int nSimboloID { get; set; }
        public int nSimboloDienteID { get; set; }
        public string sNombreDiente { get; set; }
        public string sDescripcion { get; set; }
    }
}
